language: bash
os:
  - linux
    dist: xenial
  - osx
    osx_image: xcode12.2
install:
  - bash install.sh
  - source ~/.xshrc
  - xsh upgrade -b "$TRAVIS_BRANCH"
script:
  - xsh version
  - bash test.sh
