language: bash
jobs:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode12.2
install:
  - bash install.sh -s
  - source ~/.xshrc
  - curl -fsSL https://git.io/shellspec | sh
script:
  - xsh version
  - /usr/local/lib/shellspec/shellspec -s bin/bash --no-warning-as-failure spec/xsh_spec.sh
