language: bash
jobs:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode12.2
install:
  - bash install.sh -b "$TRAVIS_BRANCH"
  - source ~/.xshrc
script:
  - xsh version
  - bash test.sh
