language: bash
git:
  depth: false
jobs:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode12.2
install:
  - bash install.sh -s
  - source ~/.xshrc
  - curl -fsSL https://git.io/shellspec | sh -s -- -y
script:
  - xsh version
  - ~/.local/bin/shellspec -s /bin/bash --no-warning-as-failure spec/xsh_spec.sh
